
spring:
  profiles:
    active: test
#spring.datasource.username=sa
#spring.datasource.password=


mybatis:
  type-aliases-package: travel.project.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    travel.project.repository: trace
    travel.project.mapper: trace




